// AI/ML Type Utilities (v1.6.0)
export type {
	ActivationFunction,
	ActivationLayer,
	AttentionConfig,
	AttentionLayer,
	Batch,
	BoundingBox,
	CheckpointConfig,
	ClassificationResult,
	Confidence,
	ConvLayer,
	DataAugmentationConfig,
	DataLoader,
	Dataset,
	DataTransform,
	DenseLayer,
	DetectionResult,
	EarlyStoppingConfig,
	EmbeddingConfig,
	EmbeddingResult,
	InferenceResult,
	Layer,
	LayerConfig,
	LayerType,
	LossFunction,
	MatrixTensor,
	MLMetric,
	Model,
	ModelConfig,
	ModelParams,
	ModelWeights,
	NeuralNetworkArchitecture,
	NormalizationLayer,
	Optimizer,
	PoolingLayer,
	Prediction,
	Probability,
	RecurrentLayer,
	ScalarTensor,
	SegmentationResult,
	Tensor,
	Tensor3D,
	Tensor4D,
	TensorDType,
	TensorRank,
	TensorShape,
	Tokenizer,
	TokenizerConfig,
	TrainingCallback,
	TrainingConfig,
	TrainingLogs,
	TransformerConfig,
	VectorTensor,
} from './ai'

// Type-level algorithms (v1.4.0)
export type {
	Find as AlgorithmFind,
	FindIndex as AlgorithmFindIndex,
	Flatten as AlgorithmFlatten,
	FlattenDeep as AlgorithmFlattenDeep,
	Includes as AlgorithmIncludes,
	IndexOf as AlgorithmIndexOf,
	Reverse as AlgorithmReverse,
	Unique as AlgorithmUnique,
	LongestCommonPrefix,
} from './algorithms'

// Assert utilities (v1.3.0)
export * from './assert'

// Async utilities (v1.3.0)
export * from './async'

// Authorization & Permissions (v1.5.0)
export type {
	ABAC,
	ABACConfig,
	AccessControl,
	ACL,
	ACLEntry,
	Action,
	Attribute,
	AttributeValue,
	AuthorizationOptions,
	AuthorizationProvider,
	ConditionOperator,
	Permission,
	PermissionCheckResult,
	PermissionCondition,
	PermissionDeny,
	PermissionGrant,
	PermissionSet,
	Policy,
	PolicyCondition,
	PolicyContext,
	PolicyEffect,
	PolicyResult,
	PolicyRule,
	RBAC,
	RBACConfig,
	Resource,
	Role,
	RoleHierarchy,
	RolePermission,
	RoleSet,
} from './auth'

// Brand types (v1.1.0)
export * from './brand'

// Caching Strategies (v1.5.0)
export type {
	ARCCache,
	Cache,
	CacheAside,
	CacheCluster,
	CacheCompressionOptions,
	CacheDecoratorOptions,
	CacheEntry,
	CacheInvalidation,
	CacheKey,
	CacheKeyBuilder,
	CacheNode,
	CacheOptions,
	CacheSerializer,
	CacheStats,
	CacheStrategy,
	CacheValue,
	ConsistentHash,
	DistributedCache,
	FIFOCache,
	HitRate,
	InvalidationEvent,
	InvalidationRule,
	InvalidationStrategy,
	LFUCache,
	LRUCache,
	MissRate,
	ReadThroughCache,
	TTLCache,
	WriteBehindCache,
	WriteThroughCache,
} from './cache'

// Collection utilities (v1.3.0) - avoid duplicates
export type {
	ListConcat,
	ListFilter,
	ListFind,
	ListIncludes,
	ListLength,
	ListReverse,
	MapDelete,
	MapGet,
	MapHas,
	MapKeys,
	MapSet,
	MapValues,
	SetAdd,
	SetDifference,
	SetHas,
	SetIntersection,
	SetIsEmpty,
	SetIsSubset,
	SetRemove,
	SetUnion,
	TypeMap,
	TypeSet,
} from './collection'

// Type-Level Compiler (v1.6.0)
export type {
	ArrayExpression,
	ArrowFunctionExpression,
	AssignmentOperator,
	ASTDeclaration,
	ASTExpression,
	ASTNode,
	ASTNodeType,
	ASTProgram,
	Property as ASTProperty,
	ASTStatement,
	BinaryExpression,
	BinaryOperator,
	Binding,
	BlockStatement,
	CallExpression,
	ClassBody,
	ClassDeclaration,
	CodeGenerator,
	CodeGeneratorOptions,
	Literal as CompilerLiteral,
	Token as CompilerToken,
	ExportDeclaration,
	ExpressionStatement,
	FormatOptions,
	FormattedCode,
	Formatter,
	ForStatement,
	FunctionDeclaration,
	GeneratedCode,
	GeneratedPosition,
	Identifier,
	IfStatement,
	ImportDeclaration,
	ImportSpecifier,
	Keyword,
	MemberExpression,
	MethodDefinition,
	ObjectExpression,
	OriginalPosition,
	ParseError,
	Parser,
	ParserConfig,
	ParserResult,
	ParseTree,
	Position,
	Printer,
	PrintOptions,
	PropertyDefinition,
	Reference,
	ReturnStatement,
	Scope,
	ScopeType,
	SourceLocation,
	SourceMap,
	SourceMapConsumer,
	TokenStream,
	TokenType,
	TransformChange,
	TransformContext,
	Transformer,
	TransformPipeline,
	TransformResult,
	TransformVisitor,
	TraverseOptions,
	TraverseVisitor,
	UnaryExpression,
	UnaryOperator,
	UpdateOperator,
	VariableDeclaration,
	VariableDeclarator,
	WhileStatement,
} from './compiler'

// Type-level concurrency (v1.4.0)
export * from './concurrency'

// Conditional types (v1.1.0)
export * from './conditional'

// Configuration Management (v1.5.0)
export type {
	Config,
	ConfigError,
	ConfigField,
	ConfigFieldType,
	ConfigFileFormat,
	ConfigLoader,
	ConfigLoaderOptions,
	ConfigPriority,
	ConfigSchema,
	ConfigValidationResult,
	ConfigValidator,
	ConfigValue,
	ConfigWarning,
	EnvConfig,
	EnvMapping,
	EnvVar,
	FeatureFlag,
	FeatureFlagConfig,
	FeatureFlags,
	FeatureFlagVariant,
	FeatureTargeting,
	ParseEnvResult,
	RemoteConfigProvider,
	Secret,
	SecretConfig,
	SecretOptions,
	SecretProvider,
	TargetingOperator,
} from './config'

// Core operations
export * from './core'

export type {
	Adler32,
	AsymmetricAlgorithm,
	Base64,
	Base64URL,
	Blake3,
	Checksum,
	ChecksumAlgorithm,
	CipherText,
	CRC32,
	CryptoContext,
	CryptoTimestamp,
	Decrypted,
	DerivedKey,
	EncodingFormat,
	EncodingResult,
	Encrypted,
	EncryptedData,
	EncryptionAlgorithm,
	EncryptionOptions,
	FNV1a,
	HashAlgorithm,
	HashFunction,
	HashInput,
	HashOutput,
	HashResult,
	Hex,
	HKDF,
	IV,
	JWT,
	JWTAlgorithm,
	JWTHeader,
	JWTPayload,
	Key,
	KeyDerivationOptions,
	KeyLength,
	KeyPair,
	KeyType,
	MACAlgorithm,
	MACResult,
	MD5,
	Nonce,
	PasswordHashOptions,
	PasswordHashResult,
	PasswordVerificationResult,
	PBKDF2,
	PlainText,
	RandomBytes,
	Salt,
	SHA256,
	SHA512,
	SignatureAlgorithm,
	SignatureResult,
	Signed,
	SigningKey,
	TagLength,
	URLEncoded,
	VerificationKey,
	Verified,
} from './crypto'

// Type-level database (v1.4.0)
export * from './database'

// Type-level data structures (v1.4.0)
export * from './datastructures'

export type {
	AddBusinessDays,
	AddDays,
	AddHours,
	AddMinutes,
	AddMonths,
	AddSeconds,
	AddWeeks,
	AddYears,
	BusinessDayConfig,
	BusinessDaysBetween,
	CalendarDate,
	CalendarMonth,
	CalendarType,
	ConvertTimezone,
	DateComponents,
	DateFormat,
	DateFormatOptions,
	DateInterval,
	DateRange,
	DateString,
	Day,
	DayOfWeek,
	DayOfYear,
	DaysBetween,
	DaysInMonth,
	DaysInYear,
	Duration,
	DurationString,
	EndOfDay,
	EndOfMonth,
	EndOfWeek,
	EndOfYear,
	FormatDate,
	Hours,
	HumanDuration,
	IsBusinessDay,
	IsLeapYear,
	ISODate,
	ISODateTime,
	ISOTimestamp,
	IsValidDate,
	IsWeekday,
	IsWeekend,
	LocalTime,
	Minutes,
	Month,
	ParseDate,
	Quarter,
	DateRange as Range,
	RelativeTime,
	RelativeTimeOptions,
	Seconds,
	StartOfDay,
	StartOfMonth,
	StartOfWeek,
	StartOfYear,
	SubtractDays,
	SubtractMonths,
	SubtractYears,
	TimeAgo,
	TimeAgoOptions,
	TimeFormat,
	TimeString,
	TimeUnit,
	Timezone,
	TimezoneOffset,
	ToUnixTimestamp,
	UnixMilliseconds,
	UnixSeconds,
	UnixTimestamp,
	UTCTime,
	WeekOfYear,
	YearsBetween,
} from './datetime'

export type {
	AccessorDecorator,
	AfterOptions,
	AroundOptions,
	BeforeOptions,
	Cached,
	Catch,
	CatchOptions,
	ChainDecorators,
	ClassDecorator,
	ClassDecoratorContext,
	ClassFieldDecoratorContext,
	ClassGetterDecoratorContext,
	ClassMethodDecoratorContext,
	ClassSetterDecoratorContext,
	ComposeDecorators,
	Decorator,
	CacheOptions as DecoratorCacheOptions,
	DecoratorFactory,
	DecoratorOptions,
	DefaultOptions,
	DefineMetadata,
	Deprecated,
	DeprecatedOptions,
	Dispose,
	Enumerable,
	EnumerableOptions,
	Frozen,
	GetMetadata,
	GetMetadataKeys,
	GetOwnMetadata,
	HasMetadata,
	Initialize,
	InitializeOptions,
	Logged,
	LogOptions,
	Memoized,
	MemoizeOptions,
	MergeDecoratorResults,
	MetadataEntry,
	MetadataKey,
	MetadataMap,
	MetadataStorage,
	MetadataValue,
	MethodDecorator,
	ParameterDecorator,
	PropertyDecorator,
	ReadOnly,
	Retry,
	RetryOptions,
	Timed,
	TimeOptions,
	Timeout,
	TimeoutOptions,
	Validate,
	ValidateOptions,
	WriteOnly,
} from './decorator'

// Deep operations
export * from './deep'

// Distributed Systems (v1.6.0)
export type {
	AppendEntriesRequest,
	AppendEntriesResponse,
	CommitResult,
	Consensus,
	ConsensusState,
	ConsistencyConfig,
	ConsistencyLevel,
	ConsistencyModel,
	Coordinator,
	DistributedLock,
	Partition as DistributedPartition,
	FailureDetector,
	GossipConfig,
	GossipMessage,
	GossipNodeState,
	Heartbeat,
	HeartbeatConfig,
	LamportClock,
	LeaderElection,
	Lease,
	LockAcquireResult,
	LockEntry,
	LockOptions,
	LockResult,
	LogEntry,
	Membership,
	MembershipEntry,
	MembershipState,
	MembershipStatus,
	MembershipUpdate,
	NodeInfo,
	NodeStatusType,
	Participant,
	ParticipantStatus,
	PartitionConfig,
	PartitionKey,
	PartitionStrategy,
	PhiAccrualConfig,
	PrepareResult,
	RaftConfig,
	ReadConcernLevel,
	Replica,
	ReplicaSet,
	ReplicaSetConfig,
	ReplicaStatus,
	Replication,
	ReplicationStrategy,
	Sharding,
	ShardMap,
	TransactionAction,
	TransactionCoordinator,
	TransactionLog,
	TransactionState,
	TwoPhaseCommit,
	VectorClock,
	Vote,
	VoteRequest,
	VoteResponse,
	WriteConcern,
} from './distributed'

// Ecosystem integration (v1.2.0)
export * from './ecosystem'

// Event-Driven Architecture (v1.5.0)
export type {
	AggregateEvents,
	BaseEvent,
	Command,
	CommandBus,
	CommandHandler,
	CommandResult,
	DeadLetterQueue,
	EventBus,
	EventBusConfig,
	EventBusHandler,
	EventBusMiddleware,
	StepStatus as EventStepStatus,
	EventStore,
	EventStream,
	EventTimestamp,
	EventVersion,
	MessageQueue,
	PublishOptions,
	Query,
	QueryBus,
	QueryHandler,
	QueryResult,
	QueueConsumer,
	QueueMessage,
	QueueProducer,
	Saga,
	SagaCompensation,
	SagaResult,
	SagaStatus,
	SagaStep,
} from './event'

export type {
	AstroFrontmatter,
	AstroGlobal,
	AstroLayout,
	AstroProps,
	AstroStaticPaths,
	ExpressHandler,
	ExpressMiddleware,
	ExpressNextFunction,
	ExpressRequest,
	ExpressResponse,
	ExpressRoute,
	FastifyHandler,
	FastifyPlugin,
	FastifyReply,
	FastifyRequest,
	FastifyRoute,
	FastifySchema,
	FreshContext,
	FreshHandler,
	FreshMiddleware,
	FreshPlugin,
	FreshRoute,
	HonoContext,
	HonoHandler,
	HonoMiddleware,
	HonoRoute,
	NestController,
	NestDecoratorMetadata,
	NestFilter,
	NestGuard,
	NestInterceptor,
	NestModule,
	NestPipe,
	NestService,
	QwikComponent,
	QwikEvent,
	QwikServerFunction,
	QwikSignal,
	QwikStore,
	QwikUseContext,
	QwikUseSignal,
	QwikUseStore,
	RemixAction,
	RemixActionData,
	RemixLoader,
	RemixLoaderData,
	RemixMeta,
	RemixRoute,
	SvelteKitAction,
	SvelteKitLayout,
	SvelteKitLoad,
	SvelteKitPage,
	SvelteKitServer,
	TRPCErrorFormatter,
	TRPCProcedureOptions,
	TRPCRouterWithMiddleware,
	UniversalAPIHandler,
	UniversalMiddleware,
} from './framework'

// Functional Programming Patterns (v1.6.0)
export type {
	Applicative,
	Compose,
	Const,
	Curry,
	Either,
	EitherOps,
	Eq,
	Err,
	Flip,
	FlipFn,
	None as FunctionalNone,
	Some as FunctionalSome,
	Functor,
	Getter,
	Identity,
	IO,
	IOOps,
	Iso,
	Left,
	Lens,
	LensPath,
	Set as LensSet,
	Maybe,
	MaybeOps,
	Monad,
	Monoid,
	Ok,
	Ord,
	Ordering,
	Over,
	Pipe,
	Predicate,
	PredicateOps,
	Prism,
	Reader,
	ReaderOps,
	Refinement,
	Result,
	ResultOps,
	Right,
	Semigroup,
	Setter,
	State,
	StateOps,
	Task,
	TaskOps,
	Traversal,
	Uncurry,
	View,
	Writer,
	WriterOps,
} from './functional'

// Function utilities (v1.1.0)
export * from './functions'

export type {
	Adapter,
	ASTTransformer,
	ASTVisitor,
	Builder,
	ClassBuilder,
	GenerateFromSchema as CodeGenerateFromSchema,
	Factory,
	FormattedOutput,
	FunctionBuilder,
	ASTNode as GenerateASTNode,
	GeneratedClass,
	GeneratedFunction,
	GeneratedInterface,
	GeneratedMethod,
	GeneratedParameter,
	GeneratedProperty,
	GeneratedType,
	GenerateFromJSON,
	GenerateFromOpenAPI,
	GenerationOptions,
	InterfaceBuilder,
	JavaScriptOptions,
	JSONOptions,
	MethodOptions,
	OutputFormat,
	OutputMetadata,
	ParameterOptions,
	PropertyOptions,
	SchemaField,
	Singleton,
	Template,
	TemplateEntry,
	TemplateError,
	TemplateLiteral,
	TemplateRegistry,
	TemplateResult,
	TemplateString,
	TemplateVariable,
	TemplateVariables,
	TypeBuilder,
	TypeScriptOptions,
	YAMLOptions,
} from './generate'

// GraphQL Integration (v1.5.0)
export * from './graphql'

// Type guards
export * from './guards'

// Type-level HTTP & API (v1.4.0)
export type {
	Middleware as HTTPMiddleware,
	HTTPStatus,
	Route,
} from './http'

// Internationalization (v1.6.0)
export type {
	CalendarConfig,
	CollationOptions,
	CollationType,
	CompiledMessage,
	CountryCode,
	Currency,
	CurrencyFormatOptions,
	Direction,
	DisplayNamesOptions,
	DisplayNamesType,
	FormattedMessage,
	CalendarType as I18nCalendarType,
	DateFormat as I18nDateFormat,
	TimeFormat as I18nTimeFormat,
	InterpolatedMessage,
	InterpolationOptions,
	LanguageCode,
	ListFormatOptions,
	ListFormatStyle,
	ListFormatType,
	Locale,
	LocaleCode,
	LocaleConfig,
	LocaleDetection,
	LocalizedCurrency,
	LocalizedDate,
	LocalizedNumber,
	LocalizedTime,
	MessageFormat,
	MessageParams,
	NumberFormat,
	NumberFormatOptions,
	NumberingSystem,
	PluralForm,
	PluralRule,
	RegionConfig,
	RegionType,
	RelativeTimeFormat,
	RelativeTimeUnit,
	RTLConfig,
	RTLLocaleChecker,
	TimeZone,
	Translation,
	TranslationKey,
	TranslationMap,
	TranslationOptions,
	TranslationResource,
	TranslationValue,
	UnitFormatOptions,
	UnitType,
} from './i18n'

// Type inference
export * from './infer'

// Type Inference Enhancements (v1.6.0)
export type {
	Assignable,
	DeepResolve,
	Equals,
	Extends,
	ExtractClass,
	ExtractConstructor,
	ExtractFunction,
	ExtractFunctionKeys,
	ExtractKeysByValue,
	ExtractMethod,
	ExtractNonFunctionKeys,
	ExtractOptionalKeys,
	ExtractProperty,
	ExtractRequiredKeys,
	FlattenType as FlattenTypeInference,
	Infer,
	InferArgs,
	InferArrayElement,
	InferFunctionParam,
	GetTypeCategory as InferGetTypeCategory,
	InferObjectValue,
	InferPromise,
	InferReturn,
	InferTupleElement,
	TypeName as InferTypeName,
	IsLiteral,
	IsNull,
	IsOptional,
	IsReadonly,
	IsUndefined,
	IsVoid,
	Narrow,
	NarrowBy,
	NarrowByTag,
	NarrowTo,
	NarrowWithDiscriminator,
	Reconstruct,
	ReconstructDeep,
	ReconstructStrict,
	ResolveArray,
	ResolveOptional,
	ResolvePromise,
	StrictExtends,
	TypeMapEntry,
	TypeMapGet,
	TypeMapHas,
	TypeMapKeys,
	TypeMapSet,
	TypeMapValues,
	Widen,
	WidenArrayElement,
	WidenLiteral,
	WidenTo,
} from './inference'

// Type-level interop (v1.4.0)
export * from './interop'

// Key utilities (v1.1.0)
export * from './keys'

// Logging & Observability (v1.5.0)
export type {
	Alert,
	AlertReceiver,
	AlertRoute,
	AlertRule,
	AlertSeverity,
	AlertStatus,
	Counter,
	Gauge,
	HealthIndicator,
	Histogram,
	InhibitRule,
	LivenessCheck,
	LogContext,
	Logger,
	LoggerConfig,
	AlertConfig as LoggingAlertConfig,
	HealthCheckResult as LoggingHealthCheckResult,
	LogEntry as LoggingLogEntry,
	MetricsRegistry as LoggingMetricsRegistry,
	TraceContext as LoggingTraceContext,
	LogLevel,
	LogTransport,
	Metric,
	MetricType,
	Monitor,
	MonitorResult,
	MonitorStatus,
	ReadinessCheck,
	Span,
	SpanEvent,
	SpanKind,
	SpanLink,
	SpanOptions,
	SpanStatus,
	Summary,
	Trace,
	Tracer,
	TraceStatus,
} from './logging'

export type {
	Abs,
	Add,
	Angle,
	BinaryToDecimal,
	BitAnd,
	BitNot,
	BitOr,
	BitXor,
	Cbrt,
	CelsiusToFahrenheit,
	CelsiusToKelvin,
	Clamp,
	Combination,
	Cos,
	Covariance,
	DecimalToBinary,
	DecimalToHex,
	DecimalToOctal,
	DegreesToGradians,
	DegreesToRadians,
	Divide,
	E,
	Exp,
	Factorial,
	FahrenheitToCelsius,
	Fibonacci,
	Floor,
	GCD,
	GradiansToDegrees,
	GreaterThan,
	GreaterThanOrEqual,
	HexToDecimal,
	InRange,
	InRangeExclusive,
	InRangeInclusive,
	IsCoprime,
	IsEven,
	IsFinite,
	IsFloat,
	IsInfinite,
	IsInteger,
	IsNaN,
	IsNegative,
	IsOdd,
	IsPositive,
	IsPrime,
	IsZero,
	KelvinToCelsius,
	LCM,
	LeftShift,
	LessThan,
	LessThanOrEqual,
	LN2,
	LN10,
	Log,
	Log2,
	LOG2E,
	Log10,
	LOG10E,
	Max,
	Mean,
	Median,
	Min,
	Mode,
	Modulo,
	Multiply,
	Neg,
	NthRoot,
	NumberToString,
	NumericEqual,
	NumericNotEqual,
	NumericRange,
	OctalToDecimal,
	Percentile,
	Permutation,
	Power,
	PrimeFactors,
	Product,
	Quartiles,
	RadiansToDegrees,
	Ratio,
	RightShift,
	Round,
	Sign,
	Sin,
	Sqrt,
	SQRT1_2,
	SQRT2,
	StdDev,
	StringToNumber,
	Subtract,
	Sum,
	Tan,
	Temperature,
	Totient,
	Trunc,
	UnsignedRightShift,
	Variance,
} from './math-advanced'

export type {
	Analyze,
	Apply,
	Compatible,
	ComposeTypes,
	Construct,
	Deconstruct,
	Depth,
	Exactly,
	ExtendsType,
	FlattenType,
	Generate,
	GenerateAll,
	IsNullable,
	IsOptionalType,
	IsReadonlyType,
	MergeTypes,
	GenerateFromSchema as MetaGenerateFromSchema,
	GetTypeCategory as MetaGetTypeCategory,
	TypeName as MetaTypeName,
	OmitTypeAtPath,
	PatternMatch,
	PickTypeAtPath,
	Reflect,
	Satisfies,
	SetTypeAtPath,
	Transform,
	TypeAtPath,
	TypeCategory,
	TypeInfo,
	Width,
} from './meta'

// Microservices Architecture (v1.5.0)
export type {
	APIGateway,
	AuthConfig,
	CircuitBreaker,
	CircuitBreakerConfig,
	CircuitBreakerState,
	CircuitBreakerStats,
	CORSConfig,
	GatewayConfig,
	GatewayMiddleware,
	GatewayRoute,
	HealthCheck,
	HealthReport,
	InstanceStatus,
	LoadBalancer,
	LoadBalancerStrategy,
	Microservice,
	RateLimit,
	ServiceClient,
	ServiceConfig,
	ServiceDiscovery,
	ServiceError,
	HealthStatus as ServiceHealthStatus,
	ServiceInstance,
	ServiceRegistry,
	ServiceRequest,
	ServiceResponse,
	RetryPolicy as ServiceRetryPolicy,
} from './microservice'

// Performance Monitoring (v1.6.0)
export type {
	AlertAction,
	AlertConfig,
	BenchmarkComparison,
	BenchmarkSuite,
	CallFrame,
	CPUMetric,
	CPUProfile,
	CPUUsage,
	HeapEdge,
	HeapMap,
	HeapNode,
	LeakedObject,
	MemoryLeakDetection,
	MemoryMetric,
	MemorySnapshot,
	MemoryStatistics,
	MemoryUsage,
	MetricsConfig,
	MetricsRegistry,
	HealthCheckResult as MonitoringHealthCheckResult,
	Performance,
	PerformanceAlert,
	PerformanceBenchmark,
	PerformanceEntry,
	PerformanceHealthCheck,
	PerformanceMeasure,
	PerformanceMetric,
	PerformanceTrace,
	PositionTick,
	ProfileFrame,
	ProfileHotspot,
	ProfileNode,
	Profiler,
	ProfileResult,
	ProfileStack,
	ProfileStatistics,
	Timing,
	TimingConfig,
	TimingEnd,
	TimingResult,
	TimingStart,
	TraceConfig,
	TraceContext,
	TraceSpan,
} from './monitoring'

// Numeric utilities (v1.1.0)
export * from './numeric'

// Object utilities (v1.3.0)
export * from './object'

// Type-level parsers (v1.4.0)
export * from './parsers'

// Path utilities (v1.1.0)
export * from './path'

// Pattern matching (v1.3.0)
export * from './pattern'

// Performance optimization (v1.2.0)
export * from './perf'

// Plugin System Types (v1.6.0)
export type {
	Extension,
	ExtensionConfig,
	ExtensionContext,
	ExtensionHandler,
	ExtensionPoint,
	ExtensionRegistry,
	ExtensionSchema,
	Hook,
	HookCallback,
	HookConfig,
	HookContext,
	HookExecutor,
	HookResult,
	HookSubscriber,
	Middleware,
	MiddlewareConfig,
	MiddlewareContext,
	MiddlewarePipeline,
	MiddlewareResult,
	Module,
	ModuleConfig,
	ModuleExport,
	ModuleImport,
	ModuleLoader,
	Plugin,
	PluginAPI,
	PluginConfig,
	PluginConfigProperty,
	PluginConfigSchema,
	PluginContext,
	PluginEventBus,
	PluginLifecycle,
	PluginLifecycleHook,
	PluginLogger,
	PluginManager,
	PluginQuery,
	PluginStore,
	Registry,
	RegistryConfig,
	RegistryEntry,
	StoredPlugin,
} from './plugin'

// Record utilities (v1.1.0)
export * from './record'

// Schema validation (v1.2.0)
export * from './schema'

export type {
	AllIndices,
	AllIndicesOf,
	AreDisjoint,
	Difference as ArrayDifference,
	ArrayEquals,
	Range as ArrayRange,
	At,
	AtOr,
	Average,
	BinarySearch,
	BinarySearchOptions,
	BinarySearchResult,
	BubbleSort,
	BucketSort,
	Chunk,
	Comparator,
	Count,
	CountBy,
	CountingSort,
	CountOccurrences,
	Drop,
	DropLastN,
	DropWhile,
	Duplicates,
	EndsWith,
	Every,
	Filter,
	FindAll,
	FindLastIndex,
	FlattenDepth,
	FrequencyMap,
	GroupBy,
	HaveCommon,
	HeapSort,
	InsertionSort,
	Interleave,
	Intersection,
	Intersperse,
	IsSubset,
	IsSuperset,
	LastIndexOf,
	LinearSearch,
	MaxElement,
	MedianElement,
	MergeSort,
	MinElement,
	ModeElement,
	MultiSortOptions,
	NonDuplicates,
	ProductElements,
	QuickSort,
	RadixSort,
	RangeStep,
	Reject,
	RemoveAll,
	RemoveAt,
	RemoveFirst,
	RotateLeft,
	RotateRight,
	Find as SearchFind,
	FindIndex as SearchFindIndex,
	Flatten as SearchFlatten,
	FlattenDeep as SearchFlattenDeep,
	Includes as SearchIncludes,
	IndexOf as SearchIndexOf,
	None as SearchNone,
	Partition as SearchPartition,
	Reverse as SearchReverse,
	Some as SearchSome,
	Unique as SearchUnique,
	Slice,
	Sort,
	SortOptions,
	SortOrder,
	Splice,
	StartsWith,
	SumElements,
	SymmetricDifference,
	Take,
	TakeFirst,
	TakeLast,
	TakeLastN,
	TakeWhile,
	Union,
	UniqueBy,
	Unzip,
	Unzip3,
	Zip,
	Zip3,
	ZipWith,
} from './search'

// Security Types (v1.6.0)
export type {
	APICredentials,
	Authentication,
	AuthError,
	AuthProvider,
	AuthResult,
	AuthStatus,
	AuthToken,
	AuthType,
	BasicCredentials,
	CertificateCredentials,
	ContentSecurityPolicy,
	Credentials,
	CSRFConfig,
	CSRFToken,
	Encryption,
	Hash,
	HashedValue,
	JWTSignOptions,
	JWTVerifyOptions,
	KeyManagement,
	KeyStatus,
	KeyUsage,
	OAuthConfig,
	OAuthCredentials,
	OAuthProviderConfig,
	OAuthProviderType,
	OAuthToken,
	PasswordHashConfig,
	PermissionCheck,
	RateLimitConfig,
	RateLimitStatus,
	RoleBasedPermission,
	SafeHTML,
	SafeURL,
	SanitizationChange,
	SanitizedInput,
	EncryptedData as SecurityEncryptedData,
	EncryptionAlgorithm as SecurityEncryptionAlgorithm,
	HashAlgorithm as SecurityHashAlgorithm,
	IV as SecurityIV,
	JWT as SecurityJWT,
	JWTHeader as SecurityJWTHeader,
	Key as SecurityKey,
	KeyPair as SecurityKeyPair,
	Salt as SecuritySalt,
	SignatureAlgorithm as SecuritySignatureAlgorithm,
	SigningKey as SecuritySigningKey,
	VerificationKey as SecurityVerificationKey,
	Session,
	SessionConfig,
	SessionData,
	SessionId,
	SessionStore,
	Signature,
	SignatureVerificationResult,
	SignedData,
} from './security'

// Type-level state machines (v1.4.0)
export * from './statemachine'

// ============================================================================
// v1.7.0 - Metaprogramming Utilities
// ============================================================================

// String utilities (v1.3.0)
export * from './string'

// ============================================================================
// v1.7.0 - Type Decorators
// ============================================================================

// Template literal utilities (v1.1.0)
export * from './template'

// ============================================================================
// v1.7.0 - Code Generation Templates
// ============================================================================

// Testing Framework Integration (v1.6.0)
export type {
	Assertion,
	AssertionError,
	AssertionMatcher,
	AssertionResult,
	Benchmark,
	BenchmarkConfig,
	BenchmarkResult,
	BenchmarkStatistics,
	Coverage,
	CoverageConfig,
	CoverageRange,
	CoverageReport,
	CoverageThreshold,
	ExpectType,
	FileCoverage,
	Fixture,
	FixtureConfig,
	FixtureContext,
	FixtureData,
	Mock,
	MockCall,
	MockConfig,
	MockResult,
	NegatedExpectType,
	Snapshot,
	SnapshotConfig,
	SnapshotMatch,
	SnapshotResult,
	Spy,
	SpyConfig,
	SuiteResult,
	TestCase,
	TestConfig,
	TestEnvironmentConfig,
	TestEnvironmentType,
	TestError,
	TestFilter,
	TestHook,
	TestHookFunction,
	TestHooksConfig,
	TestReporter,
	TestResult,
	TestResultType,
	TestRunner,
	TestRunnerResult,
	TestSuite,
	TestSummary,
} from './test-framework'

// ============================================================================
// v1.7.0 - Framework Integrations
// ============================================================================

// Type-level testing (v1.4.0)
export * from './testing'

// ============================================================================
// v1.7.0 - Type-Safe Configuration
// ============================================================================

export type {
	BuildConfig,
	ConfigAccessor,
	ConfigBuilder,
	ConfigCallback,
	ConfigChange,
	ConfigDefaults,
	ConfigPipeline,
	ConfigRule,
	ConfigRules,
	ConfigSource,
	ConfigStep,
	ConfigValidationError,
	ConfigWatcher,
	DeepPartialConfig,
	EnvField,
	EnvironmentAwareConfig,
	EnvironmentConfigLoader,
	EnvironmentName,
	EnvTransform,
	EnvValidation,
	EnvVars,
	ExtractConfigFromSchema,
	JSONConfig,
	LoadError,
	LoadErrorCode,
	LoadOptions,
	LoadResult,
	MergeConfigs,
	MergedConfig,
	MultiSourceConfig,
	PartialConfig,
	RequiredConfig,
	SecretSource,
	SecretValue,
	TOMLConfig,
	ConfigField as TypesafeConfigField,
	ConfigFieldType as TypesafeConfigFieldType,
	ConfigFileFormat as TypesafeConfigFileFormat,
	ConfigLoader as TypesafeConfigLoader,
	ConfigPriority as TypesafeConfigPriority,
	ConfigSchema as TypesafeConfigSchema,
	ConfigValidationResult as TypesafeConfigValidationResult,
	EnvConfig as TypesafeEnvConfig,
	EnvMapping as TypesafeEnvMapping,
	SecretConfig as TypesafeSecretConfig,
	YAMLConfig,
} from './typesafe-config'

// ============================================================================
// v1.7.0 - Type Visualization
// ============================================================================

// Utility types
export * from './utils'

// ============================================================================
// v1.7.0 - Type-Level Cryptography
// ============================================================================

// Validation Rules (v1.5.0)
export type {
	ArrayFieldValidator,
	BooleanFieldValidator,
	CustomValidator,
	DateFieldValidator,
	EmailConstraint,
	MaxLength,
	MaxValue,
	MinLength,
	MinValue,
	NotValidator,
	NumberFieldValidator,
	NumberSanitizer,
	ObjectFieldValidator,
	OrValidator,
	Pattern,
	SanitizationRule,
	Sanitizer,
	SanitizeResult,
	SchemaBuilder,
	StringFieldValidator,
	StringSanitizer,
	URLConstraint,
	UUIDConstraint,
	ValidationContext,
	ValidationError,
	ValidationOptions,
	ValidationRule,
	Validator,
	ValidatorResult,
} from './validation'

// ============================================================================
// v1.7.0 - Type-Level Date/Time
// ============================================================================

export type {
	AddedProperties,
	ASCIIGraph,
	ASCIIGraphOptions,
	ASCIITable,
	ASCIITableColumn,
	ASCIITableOptions,
	ASCIITree,
	ASCIITreeNode,
	ASCIITreeOptions,
	ChangedProperties,
	ColorScheme,
	Compatibility,
	Debug,
	Display,
	DocCategory,
	DocEntry,
	DocMethod,
	DocParameter,
	Expand,
	ExpandRecursively,
	GenerateDocs,
	Inspect,
	MermaidClass,
	MermaidClassDiagram,
	MermaidOptions,
	MermaidRelationship,
	Pretty,
	Printable,
	PropertyDiff,
	RemovedProperties,
	Similarity,
	TypeComparison,
	TypeDiagram,
	TypeDiff,
	Difference as TypeDifference,
	TypeDoc,
	TypeGraph,
	TypeGraphEdge,
	TypeGraphNode,
	TypeTree,
	UnchangedProperties,
	VisualizationOptions,
	TypeMap as VisualizeTypeMap,
} from './visualize'

// ============================================================================
// v1.7.0 - Type-Level Advanced Math
// ============================================================================

// WebSocket & Real-Time (v1.5.0)
export type {
	EventEmitter,
	EventListenerOptions,
	EventMap,
	EventPayload,
	Publisher,
	PubSub,
	ReadableStreamLike,
	RealTimeChannel,
	RealTimeClient,
	RealTimeMessage,
	RealTimeSubscription,
	Stream,
	StreamChunk,
	StreamReader,
	StreamWriter,
	Subscriber,
	SubscriptionOptions,
	TransformStreamLike,
	TypedEventTarget,
	WebSocketConfig,
	WebSocketEvent,
	EventHandler as WebSocketEventHandler,
	WebSocketHandler,
	WebSocketMessage,
	WebSocketOptions,
	WebSocketState,
	WritableStreamLike,
} from './websocket'

// ============================================================================
// v1.7.0 - Type-Level Sorting & Searching
// ============================================================================

// Workflow Engine (v1.5.0)
export type {
	BPMNEvent,
	BPMNEventTrigger,
	BPMNEventType,
	BPMNGateway,
	BPMNGatewayCondition,
	BPMNGatewayType,
	BPMNProcess,
	BPMNProcessType,
	BPMNTask,
	BPMNTaskType,
	ErrorHandlerResult,
	ErrorHandlingStrategy,
	ExecutionContext,
	ExecutionResult,
	ExecutionStatus,
	ExecutionStep,
	HistoryEntry,
	HistoryEvent,
	HistoryEventType,
	StepResult,
	StepType,
	TransitionAction,
	TransitionCondition,
	Workflow,
	WorkflowDefinition,
	WorkflowEngine,
	WorkflowEngineConfig,
	WorkflowError,
	WorkflowErrorHandler,
	WorkflowExecution,
	WorkflowExecutor,
	WorkflowHistory,
	WorkflowInstance,
	WorkflowPersistence,
	RetryPolicy as WorkflowRetryPolicy,
	WorkflowStatus,
	WorkflowStep,
	StepStatus as WorkflowStepStatus,
	WorkflowTimeout,
	WorkflowTransition,
} from './workflow'
