// AI/ML Type Utilities (v1.6.0)
export type {
	ActivationFunction,
	ActivationLayer,
	AttentionConfig,
	AttentionLayer,
	Batch,
	BoundingBox,
	CheckpointConfig,
	ClassificationResult,
	Confidence,
	ConvLayer,
	DataAugmentationConfig,
	DataLoader,
	Dataset,
	DataTransform,
	DenseLayer,
	DetectionResult,
	EarlyStoppingConfig,
	EmbeddingConfig,
	EmbeddingResult,
	InferenceResult,
	Layer,
	LayerConfig,
	LayerType,
	LossFunction,
	MatrixTensor,
	MLMetric,
	Model,
	ModelConfig,
	ModelParams,
	ModelWeights,
	NeuralNetworkArchitecture,
	NormalizationLayer,
	Optimizer,
	PoolingLayer,
	Prediction,
	Probability,
	RecurrentLayer,
	ScalarTensor,
	SegmentationResult,
	Tensor,
	Tensor3D,
	Tensor4D,
	TensorDType,
	TensorRank,
	TensorShape,
	Tokenizer,
	TokenizerConfig,
	TrainingCallback,
	TrainingConfig,
	TrainingLogs,
	TransformerConfig,
	VectorTensor,
} from './ai'

// Type-level algorithms (v1.4.0)
export type {
	Find,
	FindIndex,
	Flatten,
	FlattenDeep,
	Includes,
	IndexOf,
	LongestCommonPrefix,
	Reverse,
	Unique,
} from './algorithms'

// Assert utilities (v1.3.0)
export * from './assert'

// Async utilities (v1.3.0)
export * from './async'

// Authorization & Permissions (v1.5.0)
export type {
	ABAC,
	ABACConfig,
	AccessControl,
	ACL,
	ACLEntry,
	Action,
	Attribute,
	AttributeValue,
	AuthorizationOptions,
	AuthorizationProvider,
	ConditionOperator,
	Permission,
	PermissionCheckResult,
	PermissionCondition,
	PermissionDeny,
	PermissionGrant,
	PermissionSet,
	Policy,
	PolicyCondition,
	PolicyContext,
	PolicyEffect,
	PolicyResult,
	PolicyRule,
	RBAC,
	RBACConfig,
	Resource,
	Role,
	RoleHierarchy,
	RolePermission,
	RoleSet,
} from './auth'

// Brand types (v1.1.0)
export * from './brand'

// Caching Strategies (v1.5.0)
export type {
	ARCCache,
	Cache,
	CacheAside,
	CacheCluster,
	CacheCompressionOptions,
	CacheDecoratorOptions,
	CacheEntry,
	CacheInvalidation,
	CacheKey,
	CacheKeyBuilder,
	CacheNode,
	CacheOptions,
	CacheSerializer,
	CacheStats,
	CacheStrategy,
	CacheValue,
	ConsistentHash,
	DistributedCache,
	FIFOCache,
	HitRate,
	InvalidationEvent,
	InvalidationRule,
	InvalidationStrategy,
	LFUCache,
	LRUCache,
	MissRate,
	ReadThroughCache,
	TTLCache,
	WriteBehindCache,
	WriteThroughCache,
} from './cache'

// Collection utilities (v1.3.0) - avoid duplicates
export type {
	ListConcat,
	ListFilter,
	ListFind,
	ListIncludes,
	ListLength,
	ListReverse,
	MapDelete,
	MapGet,
	MapHas,
	MapKeys,
	MapSet,
	MapValues,
	SetAdd,
	SetDifference,
	SetHas,
	SetIntersection,
	SetIsEmpty,
	SetIsSubset,
	SetRemove,
	SetUnion,
	TypeMap,
	TypeSet,
} from './collection'

// Type-Level Compiler (v1.6.0)
export type {
	ArrayExpression,
	ArrowFunctionExpression,
	AssignmentOperator,
	ASTDeclaration,
	ASTExpression,
	ASTNode,
	ASTNodeType,
	ASTProgram,
	Property as ASTProperty,
	ASTStatement,
	BinaryExpression,
	BinaryOperator,
	Binding,
	BlockStatement,
	CallExpression,
	ClassBody,
	ClassDeclaration,
	CodeGenerator,
	CodeGeneratorOptions,
	Literal as CompilerLiteral,
	Token as CompilerToken,
	ExportDeclaration,
	ExpressionStatement,
	FormatOptions,
	FormattedCode,
	Formatter,
	ForStatement,
	FunctionDeclaration,
	GeneratedCode,
	GeneratedPosition,
	Identifier,
	IfStatement,
	ImportDeclaration,
	ImportSpecifier,
	Keyword,
	MemberExpression,
	MethodDefinition,
	ObjectExpression,
	OriginalPosition,
	ParseError,
	Parser,
	ParserConfig,
	ParserResult,
	ParseTree,
	Position,
	Printer,
	PrintOptions,
	PropertyDefinition,
	Reference,
	ReturnStatement,
	Scope,
	ScopeType,
	SourceLocation,
	SourceMap,
	SourceMapConsumer,
	TokenStream,
	TokenType,
	TransformChange,
	TransformContext,
	Transformer,
	TransformPipeline,
	TransformResult,
	TransformVisitor,
	TraverseOptions,
	TraverseVisitor,
	UnaryExpression,
	UnaryOperator,
	UpdateOperator,
	VariableDeclaration,
	VariableDeclarator,
	WhileStatement,
} from './compiler'

// Type-level concurrency (v1.4.0)
export * from './concurrency'

// Conditional types (v1.1.0)
export * from './conditional'

// Configuration Management (v1.5.0)
export type {
	Config,
	ConfigError,
	ConfigField,
	ConfigFieldType,
	ConfigFileFormat,
	ConfigLoader,
	ConfigLoaderOptions,
	ConfigPriority,
	ConfigSchema,
	ConfigValidationResult,
	ConfigValidator,
	ConfigValue,
	ConfigWarning,
	EnvConfig,
	EnvMapping,
	EnvVar,
	FeatureFlag,
	FeatureFlagConfig,
	FeatureFlags,
	FeatureFlagVariant,
	FeatureTargeting,
	ParseEnvResult,
	RemoteConfigProvider,
	Secret,
	SecretConfig,
	SecretOptions,
	SecretProvider,
	TargetingOperator,
} from './config'

// Core operations
export * from './core'

// Type-level database (v1.4.0)
export * from './database'

// Type-level data structures (v1.4.0)
export * from './datastructures'

// Deep operations
export * from './deep'

// Distributed Systems (v1.6.0)
export type {
	AppendEntriesRequest,
	AppendEntriesResponse,
	CommitResult,
	Consensus,
	ConsensusState,
	ConsistencyConfig,
	ConsistencyLevel,
	ConsistencyModel,
	Coordinator,
	DistributedLock,
	FailureDetector,
	GossipConfig,
	GossipMessage,
	GossipNodeState,
	Heartbeat,
	HeartbeatConfig,
	LamportClock,
	LeaderElection,
	Lease,
	LockAcquireResult,
	LockEntry,
	LockOptions,
	LockResult,
	LogEntry,
	Membership,
	MembershipEntry,
	MembershipState,
	MembershipStatus,
	MembershipUpdate,
	NodeInfo,
	NodeStatusType,
	Participant,
	ParticipantStatus,
	Partition,
	PartitionConfig,
	PartitionKey,
	PartitionStrategy,
	PhiAccrualConfig,
	PrepareResult,
	RaftConfig,
	ReadConcernLevel,
	Replica,
	ReplicaSet,
	ReplicaSetConfig,
	ReplicaStatus,
	Replication,
	ReplicationStrategy,
	Sharding,
	ShardMap,
	TransactionAction,
	TransactionCoordinator,
	TransactionLog,
	TransactionState,
	TwoPhaseCommit,
	VectorClock,
	Vote,
	VoteRequest,
	VoteResponse,
	WriteConcern,
} from './distributed'

// Ecosystem integration (v1.2.0)
export * from './ecosystem'

// Event-Driven Architecture (v1.5.0)
export type {
	AggregateEvents,
	BaseEvent,
	Command,
	CommandBus,
	CommandHandler,
	CommandResult,
	DeadLetterQueue,
	EventBus,
	EventBusConfig,
	EventBusHandler,
	EventBusMiddleware,
	StepStatus as EventStepStatus,
	EventStore,
	EventStream,
	EventTimestamp,
	EventVersion,
	MessageQueue,
	PublishOptions,
	Query,
	QueryBus,
	QueryHandler,
	QueryResult,
	QueueConsumer,
	QueueMessage,
	QueueProducer,
	Saga,
	SagaCompensation,
	SagaResult,
	SagaStatus,
	SagaStep,
} from './event'

// Functional Programming Patterns (v1.6.0)
export type {
	Applicative,
	Compose,
	Const,
	Curry,
	Either,
	EitherOps,
	Eq,
	Err,
	Flip,
	FlipFn,
	Functor,
	Getter,
	Identity,
	IO,
	IOOps,
	Iso,
	Left,
	Lens,
	LensPath,
	Set as LensSet,
	Maybe,
	MaybeOps,
	Monad,
	Monoid,
	None,
	Ok,
	Ord,
	Ordering,
	Over,
	Pipe,
	Predicate,
	PredicateOps,
	Prism,
	Reader,
	ReaderOps,
	Refinement,
	Result,
	ResultOps,
	Right,
	Semigroup,
	Setter,
	Some,
	State,
	StateOps,
	Task,
	TaskOps,
	Traversal,
	Uncurry,
	View,
	Writer,
	WriterOps,
} from './functional'

// Function utilities (v1.1.0)
export * from './functions'

// GraphQL Integration (v1.5.0)
export * from './graphql'

// Type guards
export * from './guards'

// Type-level HTTP & API (v1.4.0)
export type {
	Middleware as HTTPMiddleware,
	HTTPStatus,
	Route,
} from './http'

// Internationalization (v1.6.0)
export type {
	CalendarConfig,
	CalendarType,
	CollationOptions,
	CollationType,
	CompiledMessage,
	CountryCode,
	Currency,
	CurrencyFormatOptions,
	DateFormat,
	DateTimeFormatOptions,
	Direction,
	DisplayNamesOptions,
	DisplayNamesType,
	FormattedMessage,
	InterpolatedMessage,
	InterpolationOptions,
	LanguageCode,
	ListFormatOptions,
	ListFormatStyle,
	ListFormatType,
	Locale,
	LocaleCode,
	LocaleConfig,
	LocaleDetection,
	LocalizedCurrency,
	LocalizedDate,
	LocalizedNumber,
	LocalizedTime,
	MessageFormat,
	MessageParams,
	NumberFormat,
	NumberFormatOptions,
	NumberingSystem,
	PluralForm,
	PluralRule,
	RegionConfig,
	RegionType,
	RelativeTimeFormat,
	RelativeTimeUnit,
	RTLConfig,
	RTLLocaleChecker,
	TimeFormat,
	TimeZone,
	Translation,
	TranslationKey,
	TranslationMap,
	TranslationOptions,
	TranslationResource,
	TranslationValue,
	UnitFormatOptions,
	UnitType,
} from './i18n'

// Type inference
export * from './infer'

// Type Inference Enhancements (v1.6.0)
export type {
	Assignable,
	DeepResolve,
	Equals,
	Extends,
	ExtractClass,
	ExtractConstructor,
	ExtractFunction,
	ExtractFunctionKeys,
	ExtractKeysByValue,
	ExtractMethod,
	ExtractNonFunctionKeys,
	ExtractOptionalKeys,
	ExtractProperty,
	ExtractRequiredKeys,
	FlattenType as FlattenTypeInference,
	GetTypeCategory,
	Infer,
	InferArgs,
	InferArrayElement,
	InferFunctionParam,
	InferObjectValue,
	InferPromise,
	InferReturn,
	InferTupleElement,
	IsLiteral,
	IsNull,
	IsOptional,
	IsReadonly,
	IsUndefined,
	IsVoid,
	Narrow,
	NarrowBy,
	NarrowByTag,
	NarrowTo,
	NarrowWithDiscriminator,
	Reconstruct,
	ReconstructDeep,
	ReconstructStrict,
	ResolveArray,
	ResolveOptional,
	ResolvePromise,
	StrictExtends,
	TypeMapEntry,
	TypeMapGet,
	TypeMapHas,
	TypeMapKeys,
	TypeMapSet,
	TypeMapValues,
	TypeName,
	Widen,
	WidenArrayElement,
	WidenLiteral,
	WidenTo,
} from './inference'

// Type-level interop (v1.4.0)
export * from './interop'

// Key utilities (v1.1.0)
export * from './keys'

// Logging & Observability (v1.5.0)
export type {
	Alert,
	AlertReceiver,
	AlertRoute,
	AlertRule,
	AlertSeverity,
	AlertStatus,
	Counter,
	Gauge,
	HealthIndicator,
	Histogram,
	InhibitRule,
	LivenessCheck,
	LogContext,
	Logger,
	LoggerConfig,
	AlertConfig as LoggingAlertConfig,
	HealthCheckResult as LoggingHealthCheckResult,
	LogEntry as LoggingLogEntry,
	MetricsRegistry as LoggingMetricsRegistry,
	TraceContext as LoggingTraceContext,
	LogLevel,
	LogTransport,
	Metric,
	MetricType,
	Monitor,
	MonitorResult,
	MonitorStatus,
	ReadinessCheck,
	Span,
	SpanEvent,
	SpanKind,
	SpanLink,
	SpanOptions,
	SpanStatus,
	Summary,
	Trace,
	Tracer,
	TraceStatus,
} from './logging'

// Microservices Architecture (v1.5.0)
export type {
	APIGateway,
	AuthConfig,
	CircuitBreaker,
	CircuitBreakerConfig,
	CircuitBreakerState,
	CircuitBreakerStats,
	CORSConfig,
	GatewayConfig,
	GatewayMiddleware,
	GatewayRoute,
	HealthCheck,
	HealthReport,
	InstanceStatus,
	LoadBalancer,
	LoadBalancerStrategy,
	Microservice,
	RateLimit,
	ServiceClient,
	ServiceConfig,
	ServiceDiscovery,
	ServiceError,
	HealthStatus as ServiceHealthStatus,
	ServiceInstance,
	ServiceRegistry,
	ServiceRequest,
	ServiceResponse,
	RetryPolicy as ServiceRetryPolicy,
} from './microservice'

// Performance Monitoring (v1.6.0)
export type {
	AlertAction,
	AlertConfig,
	BenchmarkComparison,
	BenchmarkSuite,
	CallFrame,
	CPUMetric,
	CPUProfile,
	CPUUsage,
	HeapEdge,
	HeapMap,
	HeapNode,
	LeakedObject,
	MemoryLeakDetection,
	MemoryMetric,
	MemorySnapshot,
	MemoryStatistics,
	MemoryUsage,
	MetricsConfig,
	MetricsRegistry,
	HealthCheckResult as MonitoringHealthCheckResult,
	Performance,
	PerformanceAlert,
	PerformanceBenchmark,
	PerformanceEntry,
	PerformanceHealthCheck,
	PerformanceMeasure,
	PerformanceMetric,
	PerformanceTrace,
	PositionTick,
	ProfileFrame,
	ProfileHotspot,
	ProfileNode,
	Profiler,
	ProfileResult,
	ProfileStack,
	ProfileStatistics,
	Timing,
	TimingConfig,
	TimingEnd,
	TimingResult,
	TimingStart,
	TraceConfig,
	TraceContext,
	TraceSpan,
} from './monitoring'

// Numeric utilities (v1.1.0)
export * from './numeric'

// Object utilities (v1.3.0)
export * from './object'

// Type-level parsers (v1.4.0)
export * from './parsers'

// Path utilities (v1.1.0)
export * from './path'

// Pattern matching (v1.3.0)
export * from './pattern'

// Performance optimization (v1.2.0)
export * from './perf'

// Plugin System Types (v1.6.0)
export type {
	Extension,
	ExtensionConfig,
	ExtensionContext,
	ExtensionHandler,
	ExtensionPoint,
	ExtensionRegistry,
	ExtensionSchema,
	Hook,
	HookCallback,
	HookConfig,
	HookContext,
	HookExecutor,
	HookResult,
	HookSubscriber,
	Middleware,
	MiddlewareConfig,
	MiddlewareContext,
	MiddlewarePipeline,
	MiddlewareResult,
	Module,
	ModuleConfig,
	ModuleExport,
	ModuleImport,
	ModuleLoader,
	Plugin,
	PluginAPI,
	PluginConfig,
	PluginConfigProperty,
	PluginConfigSchema,
	PluginContext,
	PluginEventBus,
	PluginLifecycle,
	PluginLifecycleHook,
	PluginLogger,
	PluginManager,
	PluginQuery,
	PluginStore,
	Registry,
	RegistryConfig,
	RegistryEntry,
	StoredPlugin,
} from './plugin'

// Record utilities (v1.1.0)
export * from './record'

// Schema validation (v1.2.0)
export * from './schema'

// Security Types (v1.6.0)
export type {
	APICredentials,
	Authentication,
	AuthError,
	AuthProvider,
	AuthResult,
	AuthStatus,
	AuthToken,
	AuthType,
	BasicCredentials,
	CertificateCredentials,
	ContentSecurityPolicy,
	Credentials,
	CSRFConfig,
	CSRFToken,
	EncryptedData,
	Encryption,
	EncryptionAlgorithm,
	Hash,
	HashAlgorithm,
	HashedValue,
	IV,
	JWT,
	JWTHeader,
	JWTSignOptions,
	JWTVerifyOptions,
	Key,
	KeyManagement,
	KeyPair,
	KeyStatus,
	KeyUsage,
	OAuthConfig,
	OAuthCredentials,
	OAuthProviderConfig,
	OAuthProviderType,
	OAuthToken,
	PasswordHashConfig,
	PermissionCheck,
	RateLimitConfig,
	RateLimitStatus,
	RoleBasedPermission,
	SafeHTML,
	SafeURL,
	Salt,
	SanitizationChange,
	SanitizedInput,
	Session,
	SessionConfig,
	SessionData,
	SessionId,
	SessionStore,
	Signature,
	SignatureAlgorithm,
	SignatureVerificationResult,
	SignedData,
	SigningKey,
	VerificationKey,
} from './security'

// Type-level state machines (v1.4.0)
export * from './statemachine'

// String utilities (v1.3.0)
export * from './string'

// Template literal utilities (v1.1.0)
export * from './template'

// Testing Framework Integration (v1.6.0)
export type {
	Assertion,
	AssertionError,
	AssertionMatcher,
	AssertionResult,
	Benchmark,
	BenchmarkConfig,
	BenchmarkResult,
	BenchmarkStatistics,
	Coverage,
	CoverageConfig,
	CoverageRange,
	CoverageReport,
	CoverageThreshold,
	ExpectType,
	FileCoverage,
	Fixture,
	FixtureConfig,
	FixtureContext,
	FixtureData,
	Mock,
	MockCall,
	MockConfig,
	MockResult,
	NegatedExpectType,
	Snapshot,
	SnapshotConfig,
	SnapshotMatch,
	SnapshotResult,
	Spy,
	SpyConfig,
	SuiteResult,
	TestCase,
	TestConfig,
	TestEnvironmentConfig,
	TestEnvironmentType,
	TestError,
	TestFilter,
	TestHook,
	TestHookFunction,
	TestHooksConfig,
	TestReporter,
	TestResult,
	TestResultType,
	TestRunner,
	TestRunnerResult,
	TestSuite,
	TestSummary,
} from './test-framework'

// Type-level testing (v1.4.0)
export * from './testing'

// Utility types
export * from './utils'

// Validation Rules (v1.5.0)
export type {
	ArrayFieldValidator,
	BooleanFieldValidator,
	CustomValidator,
	DateFieldValidator,
	EmailConstraint,
	MaxLength,
	MaxValue,
	MinLength,
	MinValue,
	NotValidator,
	NumberFieldValidator,
	NumberSanitizer,
	ObjectFieldValidator,
	OrValidator,
	Pattern,
	SanitizationRule,
	Sanitizer,
	SanitizeResult,
	SchemaBuilder,
	StringFieldValidator,
	StringSanitizer,
	URLConstraint,
	UUIDConstraint,
	ValidationContext,
	ValidationError,
	ValidationOptions,
	ValidationRule,
	Validator,
	ValidatorResult,
} from './validation'

// WebSocket & Real-Time (v1.5.0)
export type {
	EventEmitter,
	EventListenerOptions,
	EventMap,
	EventPayload,
	Publisher,
	PubSub,
	ReadableStreamLike,
	RealTimeChannel,
	RealTimeClient,
	RealTimeMessage,
	RealTimeSubscription,
	Stream,
	StreamChunk,
	StreamReader,
	StreamWriter,
	Subscriber,
	SubscriptionOptions,
	TransformStreamLike,
	TypedEventTarget,
	WebSocketConfig,
	WebSocketEvent,
	EventHandler as WebSocketEventHandler,
	WebSocketHandler,
	WebSocketMessage,
	WebSocketOptions,
	WebSocketState,
	WritableStreamLike,
} from './websocket'

// Workflow Engine (v1.5.0)
export type {
	BPMNEvent,
	BPMNEventTrigger,
	BPMNEventType,
	BPMNGateway,
	BPMNGatewayCondition,
	BPMNGatewayType,
	BPMNProcess,
	BPMNProcessType,
	BPMNTask,
	BPMNTaskType,
	ErrorHandlerResult,
	ErrorHandlingStrategy,
	ExecutionContext,
	ExecutionResult,
	ExecutionStatus,
	ExecutionStep,
	HistoryEntry,
	HistoryEvent,
	HistoryEventType,
	StepResult,
	StepType,
	TransitionAction,
	TransitionCondition,
	Workflow,
	WorkflowDefinition,
	WorkflowEngine,
	WorkflowEngineConfig,
	WorkflowError,
	WorkflowErrorHandler,
	WorkflowExecution,
	WorkflowExecutor,
	WorkflowHistory,
	WorkflowInstance,
	WorkflowPersistence,
	RetryPolicy as WorkflowRetryPolicy,
	WorkflowStatus,
	WorkflowStep,
	StepStatus as WorkflowStepStatus,
	WorkflowTimeout,
	WorkflowTransition,
} from './workflow'
